### ISSUE TITLE
Not sure if the pam configuration is correct

### ISSUE THREAD

**Issue by uncomfyhalomacro** [ifreund/waylock#47]
`swaylock` has a pam configuration like this

```
#
# PAM configuration file for the swaylock screen locker. By default, it includes
# the 'login' configuration file (see /etc/pam.d/login)
#

auth include login
```

I tried using `waylock` and had problems logging in. I changed the pam config from `auth include system-auth` to `auth include login` and it fixed my issue.

**Comment by ifreund** [comment]
As far as I know, there's no universally supported standard PAM configuration and exactly what is correct depends on the Unix system used. For example, see how FreeBSD [patches the PAM configuration shipped with swaylock](https://github.com/freebsd/freebsd-ports/blob/4b8ee59e2655732220b449792255be930a67b8e8/x11/swaylock/files/patch-pam_swaylock).

I'm open to change the default config waylock ships if a more correct alternative exists. However, I believe system-auth to be fairly widely supported on linux systems and pedantically more correct than `login`. (`/etc/pam.d/login` is for the `/bin/login` program specifically). See also https://wiki.archlinux.org/title/PAM#PAM_base-stack

I chose `system-auth` because it is what xscreensaver uses and was used by the distros I looked at.

**Comment by uncomfyhalomacro** [comment]
Hello. Thanks for the quick response. I don't know much about PAM configuration but based on the link you have and the ones I saw in screenlockers openSUSE and other distros I know - they have varied configurations. [`xscreensaver`](https://build.opensuse.org/package/view_file/X11:Utilities/xscreensaver/xscreensaver.pamd?expand=1) for example in openSUSE follows a different configuration. So I guess it really depends on the Unix system as you said.

I learned new things today. Thanks. I will close this since this is a non-issue but more of a question.
